version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "ng-packagr"
          - "angular-eslint"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "typescript-eslint"
      karma:
        patterns:
          - "karma*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
