dist: xenial
sudo: false

language: node_js
node_js:
  - "13"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - ./node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn run lint
