version: "{build}"

environment:
  nodejs_version: "13.7.0"

platform:
  - x64

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn global add @angular/cli@latest
  - yarn global add codecov
  - node --version
  - yarn --version

build: off

test_script:
  - yarn install
  - yarn test
  - codecov --disable=gcov
