version: "{build}"

image: Visual Studio 2019

environment:
  nodejs_version: "13.7.0"

platform:
  - x64

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install -g @angular/cli

before_build:
  - npm install

build_script:
  - ng build ngx-semantic --prod
  - ng build docs --prod

test_script:
  - ng test ngx-semantic
  - yarn run lint

cache:
  - node_modules -> yarn.lock
  - "%LOCALAPPDATA%/Yarn"
