name: Build and Test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Angular
        run: npm install -g @angular/cli@latest
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test:ci
      - name: Report Code Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/ngx-semantic/lcov.info
          disable_search: true
      - name: Build
        run: npm run build:prod
