name: Development

on:
  push:
    branches: [ "dev" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      src_changed: ${{ steps.check_changes.outputs.src_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for changes in src directory
        id: check_changes
        run: |
          git fetch origin
          CHANGED_FILES=$(git diff --name-only origin/dev...HEAD)
          if echo "$CHANGED_FILES" | grep -q "^src/"; then
            echo "src_changed=true" >> $GITHUB_OUTPUT
          else
            echo "src_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Yarn
        run: npm install -g yarn
      - name: Setup Angular
        run: yarn global add @angular/cli@latest
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run build:prod
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist
          retention-days: 1

  tag:
    needs: build
    if: needs.build.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Tag Version
        id: tag-version
        run: |
          cd src
          NEW_VERSION=$(npm version prerelease --preid=beta)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git config --local user.email "indexz3ro@aol.com"
          git config --local user.name "CI"
          git commit -a -m "ci: version pre-release"
          git tag $NEW_VERSION
      - name: Push Tags to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

  publish:
    needs: tag
    if: needs.build.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist
      - name: Publish Lib
        run: npm publish ./dist --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: publish
    if: needs.build.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          makeLatest: "latest"
          generateReleaseNotes: true
