name: Production

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      src_changed: ${{ steps.check_changes.outputs.src_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes in src directory
        id: check_changes
        run: |
          git fetch origin
          CHANGED_FILES=$(git diff --name-only origin/master...HEAD)
          if echo "$CHANGED_FILES" | grep -q "^src/"; then
            echo "src_changed=true" >> $GITHUB_OUTPUT
          else
            echo "src_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Angular
        run: npm install -g @angular/cli@latest
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist
          retention-days: 1

  tag:
    needs: build
    if: needs.build.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Tag Version
        id: tag-version
        run: |
          cd src
          NEW_VERSION=$(npm version patch)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git config --local user.email "indexz3ro@aol.com"
          git config --local user.name "CI"
          git commit -a -m "ci: version release"
          git tag $NEW_VERSION
      - name: Push Tags to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

  publish:
    needs: tag
    if: needs.build.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./dist
      - name: Publish Lib
        run: npm publish ./dist --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: publish
    if: needs.build.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Create Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const tags_url = context.payload.repository.tags_url + "?per_page=1"
              const result = await github.request(tags_url)
              const current_tag = result.data[0].name
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: current_tag,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: current_tag,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
