name: Pull Requests

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Yarn
        run: npm install -g yarn
      - name: Setup Angular
        run: yarn global add @angular/cli@latest
      - name: Setup Codecov
        run: yarn global add codecov
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test:ci
      - name: Report Code Coverage
        run: codecov --disable=gcov
